In [2]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[2,2,3]])
b = np.array([3,4,5])

In [5]:
a

array([[1, 2, 3],
       [2, 2, 3]])

In [6]:
b

array([3, 4, 5])

In [7]:
np.add(a,b)

array([[4, 6, 8],
       [5, 6, 8]])

In [8]:
np.subtract(b,a)

array([[2, 2, 2],
       [1, 2, 2]])

In [11]:
np.divide(a,b)

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.5       , 0.6       ]])

In [12]:
np.power(a,2)

array([[1, 4, 9],
       [4, 4, 9]], dtype=int32)

In [13]:
np.power(a,b)

array([[  1,  16, 243],
       [  8,  16, 243]])